CREATE TABLE IF NOT EXISTS VEHICLE
(
    ID              INT NOT NULL AUTO_INCREMENT,
    LICENCE_PLATE   VARCHAR,
    MAKE            VARCHAR,
    MODEL           VARCHAR,
    PROD_YEAR       NUMERIC,
    COLOR           VARCHAR,
    GEAR_TYPE       VARCHAR,
    FUEL_PERCENTAGE FLOAT,
    LOT_ID          INT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID              INT NOT NULL AUTO_INCREMENT,
    SURNAME         VARCHAR,
    NAME            VARCHAR,
    PATRONYMIC_NAME VARCHAR,
    BIRTH_DATE      DATE,
    PHONE_NUMBER    VARCHAR,
    PASSWORD        VARCHAR,
    STATUS          VARCHAR,
    RENT_COUNT      INT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PARKING_LOT
(
    ID                 INT NOT NULL AUTO_INCREMENT,
    NAME               VARCHAR,
    CITY               VARCHAR,
    ADDRESS            VARCHAR,
    ADDITIONAL_PAYMENT BOOLEAN,
    IS_ACTIVE          BOOLEAN,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RENT_HISTORY
(
    ID              INT NOT NULL AUTO_INCREMENT,
    VEHICLE_NAME    VARCHAR,
    VEHICLE_ID      INT,
    START_LOT_NAME  VARCHAR,
    END_LOT_NAME    VARCHAR,
    START_RENT_TIME DATETIME,
    END_RENT_TIME   DATETIME,
    CUSTOMER_ID     INT,
    LOT_ID          INT,
    PRIMARY KEY (ID)
);